spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


#jsp视图解析
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp


#freemarker
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl


